
"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

from django.utils.csp import CSP
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent


# Carrega as variáveis do arquivo .env

load_dotenv(BASE_DIR / '.env')


# /data/web/static
# /data/web/media

DATA_DIR = BASE_DIR.parent / 'data' / 'web'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ['SECRET_KEY']


# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = bool(int(os.getenv('DEBUG', '0')))


ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv('ALLOWED_HOSTS', '').split(',')
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'blog',
    'site_setup',
    'accounts',
    'feedback',
    'chatbot',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.csp.ContentSecurityPolicyMiddleware',
    # Serve o CSS/JS com cache e compressão quando o gunicorn está no ar.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'project.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'site_setup.context_processors.site_setup',
                'accounts.context_processors.display_name',
            ],
        },
    },
]


WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'

# data/web/static

STATIC_ROOT = DATA_DIR / 'static'


MEDIA_URL = '/media/'

# /data/web/media

MEDIA_ROOT = DATA_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Sem EMAIL_HOST no .env, os e-mails só aparecem no terminal (docker compose
# logs). Com os dados do Gmail no .env, eles são enviados de verdade.

EMAIL_HOST = os.getenv('EMAIL_HOST', '')

if EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = True
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Quem recebe os avisos do site
SIGNUP_NOTIFY_EMAIL = os.getenv(
    'SIGNUP_NOTIFY_EMAIL', 'Bruno.h.souza258@gmail.com'
)
FEEDBACK_EMAIL = os.getenv('FEEDBACK_EMAIL', 'Bruno.h.souza258@gmail.com')


# Autenticação
# Para onde o usuário vai quando precisa estar logado, depois de entrar e
# depois de sair.

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'blog:index'
LOGOUT_REDIRECT_URL = 'blog:index'

# O link de "esqueci minha senha" vale por 1 hora (o padrão do Django é 3
# dias). Quanto menos tempo, menor o risco se o e-mail cair em mãos erradas.
PASSWORD_RESET_TIMEOUT = 60 * 60


# IA local (Ollama) usada pelo chat do site

OLLAMA_URL = os.getenv('OLLAMA_URL', 'http://ollama:11434')
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'qwen2.5:3b')


# Segurança
# https://docs.djangoproject.com/en/6.1/topics/security/

# Domínios extras aceitos em formulários (POST). Em produção, coloque o
# endereço do site no .env, ex.: CSRF_TRUSTED_ORIGINS="https://meublog.com"
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# JavaScript da página não consegue ler os cookies de sessão e CSRF.
# (O chat pega o token CSRF do formulário, não do cookie.)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'

# Content Security Policy: diz ao navegador de onde a página pode carregar
# scripts, estilos, fontes e imagens. Se alguém conseguir injetar um
# <script> malicioso, o navegador se recusa a executá-lo.
_csp = {
    'default-src': [CSP.SELF],
    'script-src': [CSP.SELF],
    # Fontes e estilos só do próprio site (nada de Google Fonts)
    'style-src': [CSP.SELF],
    'font-src': [CSP.SELF],
    # blob: = prévia local da foto de perfil antes de enviar (avatar.js)
    'img-src': [CSP.SELF, 'data:', 'blob:'],
    'connect-src': [CSP.SELF],
    'object-src': [CSP.NONE],
    'base-uri': [CSP.SELF],
    'form-action': [CSP.SELF],
    'frame-ancestors': [CSP.NONE],
}

if DEBUG:
    # Em desenvolvimento só avisa no console do navegador, sem bloquear,
    # porque a página de erro do Django usa scripts e estilos inline.
    SECURE_CSP_REPORT_ONLY = _csp
else:
    SECURE_CSP = _csp

    # Configurações que só fazem sentido com HTTPS (produção).
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', '1') == '1'
    # HSTS: o navegador passa a usar só HTTPS neste domínio. Começa com
    # 1 hora; aumente para 31536000 (1 ano) quando tudo estiver estável.
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '3600'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True


# Cache no banco de dados: guarda os limites de tentativas por IP. Diferente
# do cache na memória, não zera ao reiniciar o container e é compartilhado
# entre os processos do gunicorn. Tabela criada pelo "createcachetable".
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache',
    }
}

# Quantos proxies (ex.: nginx) ficam na frente do Django. Com 0, o IP do
# visitante é o REMOTE_ADDR; veja utils/rate_limit.py.
NUM_PROXIES = int(os.getenv('NUM_PROXIES', '0'))

if NUM_PROXIES > 0:
    # Atrás de um proxy com HTTPS (nginx, túnel da Cloudflare), a conexão
    # do proxy até o Django é HTTP. O proxy avisa pelo X-Forwarded-Proto
    # que o visitante usou HTTPS; sem isso o SECURE_SSL_REDIRECT entraria
    # em loop. Só ativado com proxy, porque sem ele o visitante poderia
    # forjar esse cabeçalho.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Endereço do painel admin. Troque no .env por algo difícil de adivinhar,
# ex.: ADMIN_URL="painel-a8f3k2/". Sempre termine com "/".
ADMIN_URL = os.getenv('ADMIN_URL', 'admin/').strip('/') + '/'

if not DEBUG:
    # Em produção, nomes de arquivo com hash (style.abc123.css): o navegador
    # guarda em cache por muito tempo e baixa de novo só quando muda.
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
