# Generated by Django 6.1.1 on 2026-10-02 19:28

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='url_or_path',
            field=models.CharField(max_length=2048, validators=[utils.validators.validate_safe_url]),
        ),
    ]
