# Generated by Django 6.1.1 on 2026-10-02 23:47

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_alter_menulink_url_or_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Ex.: (11) 95639-6972. Aparece no rodapé com link para o WhatsApp. Deixe em branco para não mostrar.', max_length=20, validators=[utils.validators.validate_phone], verbose_name='Telefone / WhatsApp'),
        ),
    ]
