# Generated by Django 6.1.1 on 2026-10-02 19:45

import django.db.models.deletion
import django.utils.timezone
import utils.model_validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, help_text='Deixe em branco para gerar a partir do nome.', max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='Parte da URL. Deixe em branco para gerar a partir do título.', max_length=255, unique=True)),
                ('excerpt', models.CharField(help_text='Aparece no card da página inicial e ajuda a IA a entender o post.', max_length=255, verbose_name='Resumo')),
                ('content', models.TextField(help_text='Texto do post. Deixe uma linha em branco entre parágrafos.', verbose_name='Conteúdo')),
                ('cover', models.ImageField(blank=True, default='', help_text='JPG, PNG ou WEBP. Imagens grandes são reduzidas para 1200px.', upload_to='posts/%Y/%m/', validators=[utils.model_validators.validate_cover_image], verbose_name='Capa')),
                ('is_published', models.BooleanField(default=False, help_text='Desmarcado, o post fica como rascunho e só você vê.', verbose_name='Publicado')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Use uma data futura para agendar a publicação.', verbose_name='Data de publicação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-published_at', '-id'),
            },
        ),
    ]
