# Generated by Django 6.1.1 on 2026-10-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_credit',
            field=models.CharField(blank=True, help_text='Ex.: "Foto: Fulano (CC BY-SA 4.0), via Wikimedia Commons".', max_length=255, verbose_name='Crédito da capa'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_source',
            field=models.URLField(blank=True, help_text='Link da página original da imagem.', verbose_name='Fonte da capa'),
        ),
    ]
